/*
 * Generated by JasperReports - 22/04/16 11:36
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import com.sylob.cochise.composant.util.*;
import net.sf.jasperreports.engine.*;
import java.util.*;
import com.sylob.cochise.composant.printmanager.datasource.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class listeetiquetteMatiere_1461317801671_873016 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_PATH = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillField field_article47aqp = null;
    private JRFillField field_article47code = null;
    private JRFillField field_article47designation = null;
    private JRFillField field_poids = null;
    private JRFillField field_logo = null;
    private JRFillField field_numeroLot = null;
    private JRFillField field_sigle = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_Groupe1_COUNT = null;
    private JRFillVariable variable_LIGNE_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_PATH = (JRFillParameter)pm.get("PATH");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_article47aqp = (JRFillField)fm.get("article/aqp");
        field_article47code = (JRFillField)fm.get("article/code");
        field_article47designation = (JRFillField)fm.get("article/designation");
        field_poids = (JRFillField)fm.get("poids");
        field_logo = (JRFillField)fm.get("logo");
        field_numeroLot = (JRFillField)fm.get("numeroLot");
        field_sigle = (JRFillField)fm.get("sigle");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_Groupe1_COUNT = (JRFillVariable)vm.get("Groupe1_COUNT");
        variable_LIGNE_COUNT = (JRFillVariable)vm.get("LIGNE_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("D:/ProgramFiles/workspace/CochiseRessources/WebRoot/etat/jasper");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(new Integer(1));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Object)(null);//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)("Mouvements");//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)("Quantité/ poids");//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.Object)field_logo.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.awt.Image)(IReportUtil.codeBarreC39(((java.lang.String)field_article47code.getValue())));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)("Désignation article : "+//$JR_EXPR_ID=18$
(IReportUtil.isNotEmpty(((java.lang.String)field_article47designation.getValue()))?((java.lang.String)field_article47designation.getValue()):""));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)("Code article : "+//$JR_EXPR_ID=19$
(IReportUtil.isNotEmpty(((java.lang.String)field_article47code.getValue()))?((java.lang.String)field_article47code.getValue()):""));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(str("RVF.etiquette.lot")+" : "+//$JR_EXPR_ID=20$
(IReportUtil.isNotEmpty(((java.lang.String)field_numeroLot.getValue()))?((java.lang.String)field_numeroLot.getValue()):""));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.awt.Image)(IReportUtil.codeBarreC39(((java.lang.String)field_numeroLot.getValue())));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)((IReportUtil.equals(((java.lang.String)field_sigle.getValue()), "R/S")?("/home/partage/images/sigle/RS"+".jpg"):"")//$JR_EXPR_ID=22$
	+//$JR_EXPR_ID=22$
	(IReportUtil.equals(((java.lang.String)field_sigle.getValue()), "R")?("/home/partage/images/sigle/"+((java.lang.String)field_sigle.getValue())+".jpg"):"")//$JR_EXPR_ID=22$
	+//$JR_EXPR_ID=22$
	(IReportUtil.equals(((java.lang.String)field_sigle.getValue()), "S")?("/home/partage/images/sigle/"+((java.lang.String)field_sigle.getValue())+".jpg"):""));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Boolean)(IReportUtil.equals(((java.lang.String)field_article47aqp.getValue()), "false"));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)("A\nQ\nP");//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)("Poids");//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)field_article47code.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numeroLot.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)("Quantité/ poids");//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)("Date");//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)("Date");//$JR_EXPR_ID=60$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("D:/ProgramFiles/workspace/CochiseRessources/WebRoot/etat/jasper");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(new Integer(1));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Object)(null);//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)("Mouvements");//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)("Quantité/ poids");//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.Object)field_logo.getOldValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.awt.Image)(IReportUtil.codeBarreC39(((java.lang.String)field_article47code.getOldValue())));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)("Désignation article : "+//$JR_EXPR_ID=18$
(IReportUtil.isNotEmpty(((java.lang.String)field_article47designation.getOldValue()))?((java.lang.String)field_article47designation.getOldValue()):""));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)("Code article : "+//$JR_EXPR_ID=19$
(IReportUtil.isNotEmpty(((java.lang.String)field_article47code.getOldValue()))?((java.lang.String)field_article47code.getOldValue()):""));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(str("RVF.etiquette.lot")+" : "+//$JR_EXPR_ID=20$
(IReportUtil.isNotEmpty(((java.lang.String)field_numeroLot.getOldValue()))?((java.lang.String)field_numeroLot.getOldValue()):""));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.awt.Image)(IReportUtil.codeBarreC39(((java.lang.String)field_numeroLot.getOldValue())));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)((IReportUtil.equals(((java.lang.String)field_sigle.getOldValue()), "R/S")?("/home/partage/images/sigle/RS"+".jpg"):"")//$JR_EXPR_ID=22$
	+//$JR_EXPR_ID=22$
	(IReportUtil.equals(((java.lang.String)field_sigle.getOldValue()), "R")?("/home/partage/images/sigle/"+((java.lang.String)field_sigle.getOldValue())+".jpg"):"")//$JR_EXPR_ID=22$
	+//$JR_EXPR_ID=22$
	(IReportUtil.equals(((java.lang.String)field_sigle.getOldValue()), "S")?("/home/partage/images/sigle/"+((java.lang.String)field_sigle.getOldValue())+".jpg"):""));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Boolean)(IReportUtil.equals(((java.lang.String)field_article47aqp.getOldValue()), "false"));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)("A\nQ\nP");//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)("Poids");//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)field_article47code.getOldValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numeroLot.getOldValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)("Quantité/ poids");//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)("Date");//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)("Date");//$JR_EXPR_ID=60$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("D:/ProgramFiles/workspace/CochiseRessources/WebRoot/etat/jasper");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(new Integer(1));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Object)(null);//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)("Mouvements");//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)("Quantité/ poids");//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.Object)field_logo.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.awt.Image)(IReportUtil.codeBarreC39(((java.lang.String)field_article47code.getValue())));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)("Désignation article : "+//$JR_EXPR_ID=18$
(IReportUtil.isNotEmpty(((java.lang.String)field_article47designation.getValue()))?((java.lang.String)field_article47designation.getValue()):""));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)("Code article : "+//$JR_EXPR_ID=19$
(IReportUtil.isNotEmpty(((java.lang.String)field_article47code.getValue()))?((java.lang.String)field_article47code.getValue()):""));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(str("RVF.etiquette.lot")+" : "+//$JR_EXPR_ID=20$
(IReportUtil.isNotEmpty(((java.lang.String)field_numeroLot.getValue()))?((java.lang.String)field_numeroLot.getValue()):""));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.awt.Image)(IReportUtil.codeBarreC39(((java.lang.String)field_numeroLot.getValue())));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)((IReportUtil.equals(((java.lang.String)field_sigle.getValue()), "R/S")?("/home/partage/images/sigle/RS"+".jpg"):"")//$JR_EXPR_ID=22$
	+//$JR_EXPR_ID=22$
	(IReportUtil.equals(((java.lang.String)field_sigle.getValue()), "R")?("/home/partage/images/sigle/"+((java.lang.String)field_sigle.getValue())+".jpg"):"")//$JR_EXPR_ID=22$
	+//$JR_EXPR_ID=22$
	(IReportUtil.equals(((java.lang.String)field_sigle.getValue()), "S")?("/home/partage/images/sigle/"+((java.lang.String)field_sigle.getValue())+".jpg"):""));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Boolean)(IReportUtil.equals(((java.lang.String)field_article47aqp.getValue()), "false"));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)("A\nQ\nP");//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)("Poids");//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)field_article47code.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numeroLot.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Object)(((java.util.ResourceBundle)parameter_REPORT_RESOURCE_BUNDLE.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(IReportUtil.subDataSource(((net.sf.jasperreports.engine.JRDataSource)parameter_REPORT_DATA_SOURCE.getValue()), "."));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)("dm4/140/ligneTableau.jasper");//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)("Quantité/ poids");//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)("Date");//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)("Date");//$JR_EXPR_ID=60$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
